export const siteConfig = {
  company: 'S.A Engenharia',
  yearsInBusiness: 4,
  whatsappNumber: '',
  navigation: [
    { label: 'Serviços', href: '#servicos' },
    { label: 'AutoCAD', href: '#projetos-autocad' },
    { label: 'Obras', href: '#galeria' },
    { label: 'Projetos 3D', href: '#projetos-3d' },
    { label: 'Sobre', href: '#sobre' },
    { label: 'Atendimento', href: '#atendimento' },
    { label: 'Contato', href: '#contato' },
  ],
  regions: ['São Paulo capital', 'Grande São Paulo', 'Uberaba/MG'],
  services: [
    {
      number: '01',
      title: 'Gerenciamento de obras',
      description: 'Apoio técnico para organizar a condução da obra e orientar decisões ao longo das etapas.',
      featured: true,
    },
    {
      number: '02',
      title: 'Vistoria de imóveis novos',
      description: 'Avaliação técnica das condições do imóvel novo antes de seguir com as próximas decisões.',
    },
    {
      number: '03',
      title: 'Projetos',
      description: 'Desenvolvimento de soluções de engenharia conforme a necessidade de cada projeto.',
    },
    {
      number: '04',
      title: 'Consultoria de engenharia',
      description: 'Orientação técnica para dúvidas e decisões relacionadas a imóveis e obras.',
    },
  ],
  additionalServices: ['Vistorias de imóveis', 'Acompanhamento de obras'],
  audiences: [
    { name: 'Escritórios de arquitetura', need: 'Apoio técnico para conduzir as demandas de engenharia ligadas aos projetos e às obras.' },
    { name: 'Imobiliárias', need: 'Avaliação técnica de imóveis para orientar conversas e decisões com mais clareza.' },
    { name: 'Condomínios', need: 'Consultoria e acompanhamento técnico para necessidades relacionadas aos imóveis e às obras.' },
    { name: 'Proprietários de imóveis novos', need: 'Vistoria das condições do imóvel e orientação sobre os próximos passos.' },
    { name: 'Pessoas com obras em execução', need: 'Apoio para compreender etapas, organizar a condução e tomar decisões durante a obra.' },
  ],
  values: ['Experiência', 'Qualidade de entrega', 'Relacionamento', 'Responsabilidade'],
  images: {
    logo: '/images/logo-sa-transparent.png',
    hero: {
      src: '/images/projetos/terraco-panoramico.jpg',
      width: 1086,
      height: 1448,
      alt: 'Terraço finalizado com vista panorâmica e acabamentos em madeira e pedra',
    },
    gallery: [
      {
        src: '/images/projetos/cozinha-ilha.jpg',
        width: 1086,
        height: 1448,
        alt: 'Cozinha contemporânea finalizada com ilha central em pedra clara e marcenaria verde',
        label: 'Cozinha contemporânea',
        category: 'Interiores',
      },
      {
        src: '/images/projetos/terraco-panoramico.jpg',
        width: 1086,
        height: 1448,
        alt: 'Terraço de cobertura finalizado com vista panorâmica, pergolado e churrasqueira',
        label: 'Terraço panorâmico',
        category: 'Área externa',
      },
      {
        src: '/images/projetos/suite-janela-canto.jpg',
        width: 1086,
        height: 1448,
        alt: 'Suíte luminosa finalizada com piso de madeira e ampla janela de canto',
        label: 'Suíte com luz natural',
        category: 'Interiores',
      },
      {
        src: '/images/projetos/sala-varanda-churrasqueira.jpg',
        width: 1086,
        height: 1448,
        alt: 'Sala integrada à varanda com churrasqueira e vista urbana',
        label: 'Sala e varanda integradas',
        category: 'Acabamentos',
      },
      {
        src: '/images/projetos/sala-varanda-urbana.jpg',
        width: 1086,
        height: 1448,
        alt: 'Sala finalizada com piso amadeirado e varanda voltada para a cidade',
        label: 'Sala com varanda urbana',
        category: 'Acabamentos',
      },
      {
        src: '/images/projetos/banheiro-cinza.jpg',
        width: 1086,
        height: 1448,
        alt: 'Banheiro compacto finalizado com revestimento cinza e bancada em granito preto',
        label: 'Banheiro em tons de cinza',
        category: 'Detalhes',
      },
      {
        src: '/images/projetos/banheiro-marmorizado.jpg',
        width: 1086,
        height: 1448,
        alt: 'Banheiro finalizado com porcelanato marmorizado e bancada clara',
        label: 'Banheiro marmorizado',
        category: 'Detalhes',
      },
    ],
    autocadProjects: [
      {
        src: '/images/autocad/implantacao.png',
        width: 768,
        height: 508,
        alt: 'Projeto de implantação em AutoCAD com planta do terreno e indicação dos elementos construtivos',
        label: 'Implantação',
        category: 'AutoCAD',
        description: 'Organização da edificação no terreno e definição dos elementos de implantação.',
      },
      {
        src: '/images/autocad/planta-terreo.png',
        width: 768,
        height: 516,
        alt: 'Planta técnica do pavimento térreo desenvolvida em AutoCAD',
        label: 'Planta do térreo',
        category: 'AutoCAD',
        description: 'Distribuição dos ambientes, acessos e circulações no pavimento térreo.',
      },
      {
        src: '/images/autocad/planta-superior.png',
        width: 768,
        height: 516,
        alt: 'Planta técnica do pavimento superior desenvolvida em AutoCAD',
        label: 'Planta superior',
        category: 'AutoCAD',
        description: 'Detalhamento da organização e das dimensões do pavimento superior.',
      },
      {
        src: '/images/autocad/corte-fachada.png',
        width: 768,
        height: 508,
        alt: 'Prancha técnica com corte e fachada da edificação desenvolvida em AutoCAD',
        label: 'Corte e fachada',
        category: 'AutoCAD',
        description: 'Leitura das alturas, níveis e composição externa da edificação.',
      },
    ],
    technicalProjects: [
      {
        src: '/images/projetos-3d/apartamento-modelo-3d.jpg',
        width: 1448,
        height: 1086,
        alt: 'Modelo tridimensional de apartamento completo com ambientes, mobiliário e varanda',
        label: 'Apartamento completo',
        category: 'Modelo 3D',
        description: 'Estudo espacial integrado dos ambientes, circulações e distribuição do mobiliário.',
      },
      {
        src: '/images/projetos-3d/cozinha-perspectiva-3d.jpg',
        width: 1448,
        height: 1086,
        alt: 'Perspectiva tridimensional de cozinha planejada com ilha central',
        label: 'Cozinha planejada',
        category: 'Perspectiva 3D',
        description: 'Visualização de layout, marcenaria, equipamentos e áreas de trabalho.',
      },
      {
        src: '/images/projetos-3d/banheiro-modelo-3d.jpg',
        width: 1448,
        height: 1086,
        alt: 'Modelo tridimensional de banheiro com bancada, box e detalhamento de revestimentos',
        label: 'Banheiro detalhado',
        category: 'Modelo 3D',
        description: 'Definição visual de louças, metais, revestimentos e proporções do espaço.',
      },
      {
        src: '/images/projetos-3d/sala-varanda-estudo-3d.jpg',
        width: 1448,
        height: 1086,
        alt: 'Estudo tridimensional de sala integrada à varanda gourmet',
        label: 'Sala e varanda integradas',
        category: 'Estudo 3D',
        description: 'Integração entre área social e varanda para antecipar decisões do projeto.',
      },
    ],
  },
} as const

export type ServiceInterest =
  | 'Gerenciamento de obras'
  | 'Vistoria de imóvel novo'
  | 'Projetos'
  | 'Consultoria de engenharia'
  | 'Vistoria de imóveis'
  | 'Acompanhamento de obras'
